#!/usr/bin/env bash
set -euo pipefail

REPO="https://github.com/greyxp1/nixos-config.git"
FLAKE_ATTR="nixos"
WORK_DIR="/tmp/nixos-config"

# ── 1. Clone config ───────────────────────────────────────────────────────────
rm -rf "$WORK_DIR"
git clone "$REPO" "$WORK_DIR"
cd "$WORK_DIR"

# ── 2. Disk selection ─────────────────────────────────────────────────────────
echo "--------------------------------------------------------------------------------"
echo "Available disks:"
echo

ISO_SOURCE=$(findmnt -n -o SOURCE /iso 2>/dev/null || true)
ISO_DISK=""
[[ -n "$ISO_SOURCE" ]] && ISO_DISK=$(lsblk -no PKNAME "$ISO_SOURCE" 2>/dev/null || true)

mapfile -t DISK_NAMES < <(
  lsblk -dn -o NAME,TYPE -e 7 \
    | awk '$2=="disk"{print $1}' \
    | grep -v "^${ISO_DISK}$" \
  || true
)
[[ ${#DISK_NAMES[@]} -eq 0 ]] && { echo "ERROR: No eligible disks found."; exit 1; }

for i in "${!DISK_NAMES[@]}"; do
  printf "[%d] /dev/%s  %s  %s\n" "$i" \
    "${DISK_NAMES[$i]}" \
    "$(lsblk -dno SIZE  "/dev/${DISK_NAMES[$i]}")" \
    "$(lsblk -dno MODEL "/dev/${DISK_NAMES[$i]}")"
done
echo

exec < /dev/tty
read -rp "Install to disk (number): " CHOICE
[[ -z "${DISK_NAMES[$CHOICE]+x}" ]] && { echo "Invalid choice."; exit 1; }

DEV="/dev/${DISK_NAMES[$CHOICE]}"
echo "Selected: $DEV"
read -rp "DANGER: This will WIPE $DEV. Are you sure? (y/n): " CONFIRM
[[ "$CONFIRM" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }

# ── 3. Detect firmware ────────────────────────────────────────────────────────
if [[ -d /sys/firmware/efi/efivars ]]; then UEFI=true; else UEFI=false; fi
echo "Firmware: $( $UEFI && echo UEFI || echo BIOS/Legacy )"

# ── 4. Partition and format ───────────────────────────────────────────────────
# NVMe and MMC devices use a 'p' separator before the partition number.
if [[ "$DEV" =~ (nvme|mmcblk) ]]; then PART="${DEV}p"; else PART="$DEV"; fi

echo "Wiping and partitioning $DEV..."
sudo wipefs -af "$DEV"
sudo parted -s "$DEV" mklabel gpt

if $UEFI; then
  sudo parted -s "$DEV" mkpart ESP  fat32  1MiB    1025MiB
  sudo parted -s "$DEV" mkpart root ext4   1025MiB 100%
  sudo parted -s "$DEV" set 1 esp on
  sudo mkfs.fat  -F 32 -n NIXBOOT "${PART}1"
  sudo mkfs.ext4 -F    -L nixos   "${PART}2"
  sudo mount /dev/disk/by-label/nixos   /mnt
  sudo mkdir -p /mnt/boot
  sudo mount /dev/disk/by-label/NIXBOOT /mnt/boot
else
  # GPT + BIOS-boot partition: GRUB writes its core image here.
  sudo parted -s "$DEV" mkpart bios_boot 1MiB  2MiB
  sudo parted -s "$DEV" mkpart root ext4 2MiB  100%
  sudo parted -s "$DEV" set 1 bios_grub on
  sudo mkfs.ext4 -F -L nixos "${PART}2"
  sudo mount /dev/disk/by-label/nixos /mnt
fi

# ── 5. Temporary swap (for the installer only) ────────────────────────────────
sudo fallocate -l 4G /mnt/.swapfile-install
sudo chmod 600       /mnt/.swapfile-install
sudo mkswap          /mnt/.swapfile-install
sudo swapon          /mnt/.swapfile-install

# ── 6. Generate hardware configuration ───────────────────────────────────────
# nixos-generate-config inspects /mnt and writes every driver, UUID, and
# hardware detail the target machine needs — impossible to know ahead of time.
echo "Detecting hardware..."
sudo nixos-generate-config --root /mnt --show-hardware-config > hardware-configuration.nix

# ── 7. Append bootloader config to hardware-configuration.nix ─────────────────
# nixos-generate-config ends the file with a '}'. We remove that last line,
# append the correct bootloader configuration for this specific machine,
# and then close the bracket.

# Remove the final '}'
head -n -1 hardware-configuration.nix > temp.nix && mv temp.nix hardware-configuration.nix

if $UEFI; then
  # --- Generate Secure Boot keys in the installer environment ---
  # This is required because Lanzaboote needs to sign the kernel during nixos-install.
  echo "Generating Secure Boot keys..."
  sudo mkdir -p /var/lib/sbctl
  # Run sbctl from a temporary nix-shell to create the keys
  sudo nix --extra-experimental-features "nix-command flakes" \
    shell nixpkgs#sbctl -c sbctl create-keys

  # Inject UEFI + Lanzaboote configuration
  cat >> hardware-configuration.nix << 'NIXEOF'

  # --- Autogenerated Bootloader (UEFI/Lanzaboote) ---
  boot.loader.systemd-boot.enable = lib.mkForce false;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.lanzaboote = {
    enable = true;
    pkiBundle = "/var/lib/sbctl";
  };

  # Ensure sbctl is available on the installed system
  environment.systemPackages = [ pkgs.sbctl ];
}
NIXEOF

# --- Copy the keys to the new system so they persist after reboot ---
  sudo mkdir -p /mnt/var/lib/sbctl
  sudo cp -r /var/lib/sbctl/* /mnt/var/lib/sbctl/

else
  # Inject BIOS/GRUB configuration
  # Notice we don't quote 'NIXEOF' here so bash expands $DEV
  cat >> hardware-configuration.nix << NIXEOF

  # --- Autogenerated Bootloader (BIOS/GRUB) ---
  boot.loader.grub = {
    enable = true;
    device = "$DEV";
  };
}
NIXEOF
fi

# Stage the modified file for the flake
git add -f hardware-configuration.nix

# ── 8. Install ────────────────────────────────────────────────────────────────
echo "Installing NixOS..."
sudo nixos-install --root /mnt --flake ".#$FLAKE_ATTR" --no-root-passwd

# ── 9. Persist config on installed system ────────────────────────────────────
# Copies the full repo (including machine-specific generated files) to
# /etc/nixos so `nixos-rebuild switch --flake /etc/nixos#nixos` works after
# first boot with no extra steps.
sudo cp -rT "$WORK_DIR" /mnt/etc/nixos

echo "Installation complete! Rebooting..."
sudo reboot
