# Generated by 'nixos-generate-config' for main-pc.
# Re-run 'nixos-generate-config --show-hardware-config' and update this file
# if you change physical hardware.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules          = [ ];
  boot.kernelModules                 = [ "kvm-amd" ];
  boot.extraModulePackages           = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4ce7ab42-22f0-4960-bf1c-bf9f17dd2465";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/B1CC-BE3C";
    fsType  = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform              = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode  = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
